---

name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          . .envrc
          task deps-install

      - name: Build Ubuntu with debos
        run: |
          . .envrc
          task ubuntu
