---

name: Build

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          . .envrc
          task deps-install

      - name: Build Ubuntu with debos
        run: |
          . .envrc
          task ubuntu

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/ubuntu-focal-amd64.cpio.gz
            out/ubuntu-focal-amd64.vmlinuz
